name: nyc_rest
channels:
  - conda-forge
  - defaults
dependencies:
- python==3.9.*
- ipykernel
- ipython>=7.15
- vega_datasets=0.9.0
- altair_saver
- selenium<4.3.0
- scikit-learn>=1.0
- pandas>=1.3.*
- requests>=2.24.0
- dataframe_image=0.1.1
- scipy=1.9.3
- matplotlib=3.6.2
- matplotlib-base=3.6.2
- matplotlib-inline=0.1.6
- pip:
  - docopt-ng==0.8.*
  - joblib==1.1.0
  - mglearn
  - psutil>=5.7.2
  - vl-convert-python==0.5.0