name: nyc_rest
channels:
  - conda-forge
  - defaults
dependencies:
- Python=3.11.0
- docopt=0.6.2
- ipykernel=6.17
- ipython=8.6.0
- vega_datasets=0.9.0
- altair_saver=0.5.0
- selenium=4.2.0
- scikit-learn=1.1.3
- pandas=1.5.2
- requests=2.28.1
- dataframe_image=0.1.1
- scipy=1.9.3
- matplotlib=3.6.2
- matplotlib-base=3.6.2
- matplotlib-inline=0.1.6
- pip:
  - joblib==1.1.0
  - mglearn==0.1.9
  - psutil>=5.7.2
  - vl-convert-python==0.5.0