name: 'nyc_rest'
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - matplotlib>=3.2.2
  - scikit-learn>=1.0
  - pandas>=1.3.*
  - requests>=2.24.0
  - graphviz
  - python-graphviz
  - python==3.9.*
  - ipykernel
  - ipython>=7.15
  - vega_datasets
  - altair_saver
  - selenium<4.3.0
  - pip
  - pip:
    - rpy2