name: 'nyc_rest'
channels:
  - conda-forge
  - defaults
dependencies:
- docopt=0.6.2
- ipykernel
- ipython>=7.15
- vega_datasets
- altair_saver
- selenium<4.3.0
- matplotlib>=3.2.2
- scikit-learn>=1.0
- pandas>=1.3.*
- requests>=2.24.0
- pip:
  - joblib==1.1.0
  - mglearn
  - psutil>=5.7.2